### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by lgarcin** [jpsenior/sphinx-execute-code#1]
Could it be possible to support Python3 ?

**Comment by jpsenior** [comment]
Sure, would be happy to. I'll let you know when this is done and pypi updated.

**Comment by rabernat** [comment]
This package looks perfect for me, but I also would need python 3 support.

Any update on progress towards this?

**Comment by cwirz** [comment]
Done with #3

**Comment by joamatab** [comment]
I think the code is not still python3 compatible

Running Sphinx v2.1.2

Exception occurred:
  File "/Users/joaquin/miniconda3/lib/python3.7/site-packages/sphinx/registry.py", line 473, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/Users/joaquin/miniconda3/lib/python3.7/site-packages/sphinx_execute_code/__init__.py", line 81
    exec code
            ^
SyntaxError: Missing parentheses in call to 'exec'
The full traceback has been saved in /var/folders/hq/3c54vd0s21911s3rjjj2csj00000gn/T/sphinx-err-xi7nygqb.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 2

**Comment by wlievens** [comment]
I get this issue

```
    exec code
            ^
SyntaxError: Missing parentheses in call to 'exec'
```

I assume this is a python 2/3 issue?

**Comment by cwirz** [comment]
@wlievens use my fork: https://github.com/cwirz/sphinx-execute-code

**Comment by Freed-Wu** [comment]
> Exception occurred:
  File "/home/wzy/.local/lib/python3.10/site-packages/sphinx_execute_code/__init__.py", line 77, in execute_code
    output = StringIO.StringIO()
AttributeError: type object '_io.StringIO' has no attribute 'StringIO'

Cannot work in python3.10?

**Comment by cwirz** [comment]
@Freed-Wu my version should work #3

**Comment by Freed-Wu** [comment]
Thanks for your reply. :smile: But I found my requirement is beyond this package so I have to create a [new package](https://pypi.org/project/sphinxcontrib-eval) for myself.
